services:
  gshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gshare_manager
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
    environment:
      - TZ=Asia/Seoul
      - FLASK_PORT=5000
      - LOG_LEVEL=INFO
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      - gshare_network

networks:
  gshare_network:
    driver: bridge
